version: "3.5"
x-services-volume: &services-volume
  type: bind

services:
  # node:
  #   container_name: node
  #   build:
  #     context: ./
  #   hostname: node
  #   networks:
  #     - docker_network
  #   ports:
  #     - 80:80
  #     - 4000:4000
  #   environment:
  #     VERSION: v1
  #     DB_USER: table_admin
  #     DB_PASSWORD: HeLLo!1
  #     DB_HOST: localhost
  #     DB_PORT: 5432
  postgres:
    container_name: postgres
    build:
      context: ./cmd/db
    volumes:
      - <<: *services-volume
        source: ${HOST}/postgres
        target: /var/lib/postgres
    ports:
      - 5432:5432
    hostname: postgres
    networks:
      - docker_network
    environment:
      #PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_shop
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: table_admin
      POSTGRES_PASSWORD: ${USERPWD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8

networks:
  docker_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
